name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: downinahill/.github/workflows/tryhackme-badge-wokflow@main
        with:
          # Replace with your tryhackme username
          username: "<Nameless23>"
          GITHUB_TOKEN: ${{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}}
